/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Biomass_animation_v02.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Biomass_animation_v02.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[1.57, -5.57, 0.81]}>
          <mesh name="Cylinder043" geometry={nodes.Cylinder043.geometry} material={materials.Black} position={[0.27, 0.37, 0.59]} scale={[0.03, 2.34, 0.03]} />
          <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Black} position={[5.14, -1.79, 0.58]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.31, 0.03]} />
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.Black} position={[-0.63, -0.05, 0.58]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.31, 0.03]} />
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.Black} position={[1.42, 1.76, 0.58]} rotation={[0, 0, -Math.PI]} scale={[0.03, 0.17, 0.03]} />
          <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.Black} position={[-1.19, -1.02, 0.58]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.31, 0.03]} />
          <mesh name="Cylinder035" geometry={nodes.Cylinder035.geometry} material={materials.Black} position={[-1.77, 0.46, 0.58]} rotation={[0, 0, -Math.PI]} scale={[0.03, 0.16, 0.03]} />
          <mesh name="Cylinder036" geometry={nodes.Cylinder036.geometry} material={materials.Black} position={[-6.05, -0.02, 0.58]} rotation={[0, 0, -Math.PI]} scale={[0.03, 0.29, 0.03]} />
          <mesh name="Cylinder037" geometry={nodes.Cylinder037.geometry} material={materials.Black} position={[0.58, 1.25, 0.58]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.31, 0.03]} />
          <mesh name="Cylinder038" geometry={nodes.Cylinder038.geometry} material={materials.Black} position={[5.65, -1.29, 0.58]} rotation={[0, 0, -Math.PI]} scale={[0.03, 0.16, 0.03]} />
          <mesh name="Cylinder039" geometry={nodes.Cylinder039.geometry} material={materials.Black} position={[5.14, -1.48, 0.58]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.31, 0.03]} />
          <mesh name="Cylinder040" geometry={nodes.Cylinder040.geometry} material={materials.Black} position={[1.9, -1.16, 0.58]} rotation={[0, 0, -Math.PI]} scale={[0.03, 0.24, 0.03]} />
          <mesh name="Cylinder041" geometry={nodes.Cylinder041.geometry} material={materials.Black} position={[1.32, 1.25, 0.58]} rotation={[Math.PI / 2, 0, Math.PI]} />
          <mesh name="Cylinder042" geometry={nodes.Cylinder042.geometry} material={materials.Black} position={[1.8, -1.49, 0.58]} rotation={[Math.PI / 2, 0, Math.PI]} />
          <mesh name="Cylinder044" geometry={nodes.Cylinder044.geometry} material={materials.Black} position={[5.55, -1.79, 0.58]} rotation={[Math.PI / 2, 0, Math.PI]} />
          <mesh name="Cylinder045" geometry={nodes.Cylinder045.geometry} material={materials.Black} position={[-1.67, -0.05, 0.58]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh name="Cylinder046" geometry={nodes.Cylinder046.geometry} material={materials.Black} position={[-5.96, -1.02, 0.58]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh name="Plane004_Plane003" geometry={nodes.Plane004_Plane003.geometry} material={materials['Material.022']} position={[-0.01, -0.11, 28.3]} rotation={[Math.PI / 2, 0, 0]} scale={[3.71, 1, 1]} />
        <mesh name="Annelids" geometry={nodes.Annelids.geometry} material={materials['Material.025']} position={[0.27, -15.05, 9.47]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_7@3x" geometry={nodes['Artboard_4_copy_7@3x'].geometry} material={materials['Artboard 4 copy 7@3x']} position={[-0.02, 0.32, 0.01]} scale={-0.66} />
        </mesh>
        <mesh name="Cnidarians" geometry={nodes.Cnidarians.geometry} material={materials['Material.026']} position={[0.35, -14.83, 9.51]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_15@3x" geometry={nodes['Artboard_4_copy_15@3x'].geometry} material={materials['Artboard 4 copy 15@3x']} position={[-0.01, 0.26, 0]} scale={0.75} />
        </mesh>
        <mesh name="Fish" geometry={nodes.Fish.geometry} material={materials['Material.027']} position={[0.32, -15.15, 9.49]} rotation={[0, 1.14, Math.PI / 2]}>
          <mesh name="Artboard_4_copy_5@3x001" geometry={nodes['Artboard_4_copy_5@3x001'].geometry} material={materials['Artboard 4 copy 5@3x']} position={[0.03, 0.46, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.7} />
        </mesh>
        <mesh name="Humans" geometry={nodes.Humans.geometry} material={materials['Material.024']} position={[0.19, -15.07, 9.42]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_10@3x" geometry={nodes['Artboard_4_copy_10@3x'].geometry} material={materials['Artboard 4 copy 10@3x']} position={[0, 0.21, -0.01]} scale={0.71} />
        </mesh>
        <mesh name="Livestock" geometry={nodes.Livestock.geometry} material={materials['Material.024']} position={[0.61, -15.11, 9.61]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_11@3x" geometry={nodes['Artboard_4_copy_11@3x'].geometry} material={materials['Artboard 4 copy 11@3x']} position={[-0.03, 0.24, -0.01]} scale={0.74} />
        </mesh>
        <mesh name="Mollusks" geometry={nodes.Mollusks.geometry} material={materials['Material.027']} position={[0.28, -15.16, 9.46]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_14@3x" geometry={nodes['Artboard_4_copy_14@3x'].geometry} material={materials['Artboard 4 copy 14@3x']} position={[0, 0.33, -0.01]} scale={0.75} />
        </mesh>
        <mesh name="Nematodes" geometry={nodes.Nematodes.geometry} material={materials['Material.025']} position={[0.47, -15.28, 9.19]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_9@3x001" geometry={nodes['Artboard_4_copy_9@3x001'].geometry} material={materials['Artboard 4 copy 9@3x']} position={[0, 0.15, -0.01]} scale={0.42} />
        </mesh>
        <mesh name="Wild_Birds" geometry={nodes.Wild_Birds.geometry} material={materials['Material.024']} position={[0.29, -14.9, 9.46]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_13@3x001" geometry={nodes['Artboard_4_copy_13@3x001'].geometry} material={materials['Artboard 4 copy 13@3x']} position={[0, 0.08, 0]} scale={0.22} />
        </mesh>
        <mesh name="Wild_Mammals" geometry={nodes.Wild_Mammals.geometry} material={materials['Material.024']} position={[0.06, -15.08, 9.36]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_12@3x001" geometry={nodes['Artboard_4_copy_12@3x001'].geometry} material={materials['Artboard 4 copy 12@3x']} position={[0, 0.11, -0.01]} scale={0.23} />
        </mesh>
        <mesh name="Archaea" geometry={nodes.Archaea.geometry} material={materials.Bacteria} position={[6.42, 2, -1.01]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Artboard_4_copy_2@3x" geometry={nodes['Artboard_4_copy_2@3x'].geometry} material={materials['Artboard 4 copy 2@3x']} position={[0.05, 0.98, -0.05]} rotation={[0, 0, -0.01]} scale={1.17} />
        </mesh>
        <mesh name="Bacteria" geometry={nodes.Bacteria.geometry} material={materials.Bacteria} position={[4.63, 3.14, -4.55]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Artboard_4@3x" geometry={nodes['Artboard_4@3x'].geometry} material={materials['Artboard 4@3x']} position={[-0.02, 2.1, 0.09]} scale={1.87} />
        </mesh>
        <mesh name="Fungi" geometry={nodes.Fungi.geometry} material={materials.Fungi} position={[-0.72, 2.19, -1.07]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Artboard_4_copy_4@3x001" geometry={nodes['Artboard_4_copy_4@3x001'].geometry} material={materials['Artboard 4 copy 4@3x']} position={[0.03, 1.16, -0.02]} rotation={[0, Math.PI / 2, 0]} scale={1.26} />
        </mesh>
        <mesh name="Protists" geometry={nodes.Protists.geometry} material={materials.Bacteria} position={[7.86, 1.83, 0.8]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Artboard_4_copy_3@3x" geometry={nodes['Artboard_4_copy_3@3x'].geometry} material={materials['Artboard 4 copy 3@3x']} position={[-0.06, 0.81, 0.02]} rotation={[0, Math.PI / 2, 0]} scale={1.17} />
        </mesh>
        <mesh name="Plants" geometry={nodes.Plants.geometry} material={materials.Plants} position={[-4.04, 4.81, -6.51]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={3.36}>
          <mesh name="Artboard_4_copy@3x" geometry={nodes['Artboard_4_copy@3x'].geometry} material={materials['Artboard 4 copy@3x']} position={[-0.04, 1.18, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.54} />
        </mesh>
        <mesh name="Animals" geometry={nodes.Animals.geometry} material={materials.Animals} position={[0.73, 1.75, 0.96]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.63}>
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-1.14, -1.13, 0.02]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[1.1, 0.02, 0.57]} />
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-1.14, 1.13, 0.02]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.1, 0.02, 0.56]} />
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-1.17, 0, 1.1]} rotation={[Math.PI, 0, 1.57]} scale={[1.1, 0.02, 0.49]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-1.17, 0, -1.1]} rotation={[0, 0, -1.57]} scale={[1.1, 0.02, 0.49]} />
          <mesh name="Artboard_4_copy_4@3x002" geometry={nodes['Artboard_4_copy_4@3x002'].geometry} material={materials['Artboard 4 copy 4@3x.001']} position={[0.1, 1.19, -0.03]} rotation={[0, Math.PI / 2, 0]} scale={[1.78, 0.73, 0.73]} />
        </mesh>
        <mesh name="Marine_Arthropods" geometry={nodes.Marine_Arthropods.geometry} material={materials['Material.026']} position={[0.38, -15.09, 9.49]} rotation={[Math.PI / 2, 0, 0.43]} scale={1.07}>
          <mesh name="Artboard_4_copy_6@3x" geometry={nodes['Artboard_4_copy_6@3x'].geometry} material={materials['Artboard 4 copy 6@3x']} position={[-0.02, 0.46, 0]} scale={[0.8, 0.89, 0.8]} />
        </mesh>
        <mesh name="Virus" geometry={nodes.Virus.geometry} material={materials.Material} position={[15, 1.34, 2.44]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.006']} position={[-0.01, 0.31, 0]} scale={0.22} />
        </mesh>
        <mesh name="Arthropods" geometry={nodes.Arthropods.geometry} material={materials['Material.025']} position={[0.49, -15.23, 9.57]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_8@3x" geometry={nodes['Artboard_4_copy_8@3x'].geometry} material={materials['Artboard 4 copy 8@3x']} position={[0, 0.31, 0.01]} scale={0.72} />
        </mesh>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Rollout} position={[0.98, -2.49, 9.28]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.72, 0.08]} />
        <mesh name="LUNA" geometry={nodes.LUNA.geometry} material={materials['Material.004']} position={[1.83, -7.41, 1.37]} scale={0.51}>
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.005']} position={[-0.02, -0.02, 1.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.72} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Biomass_animation_v02.glb')
