/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 .\\public\\Camera.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Camera.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 2.105, 0]} scale={1.086}>
          <group name="Armature" position={[0, -1.057, 0]} scale={0.921}>
            <primitive object={nodes.Bone} />
            <primitive object={nodes.Bone001} />
            <primitive object={nodes.neutral_bone} />
            <skinnedMesh name="Animals" geometry={nodes.Animals.geometry} material={materials.Animals} skeleton={nodes.Animals.skeleton}>
              <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.61, 1.417, -0.016]} rotation={[0, 1.571, 0]} scale={[0.652, 0.01, 0.31]} />
              <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[0.631, 1.426, -0.016]} rotation={[3.141, -1.571, 0]} scale={[0.628, 0.01, 0.31]} />
              <mesh name="Animals_Icon" geometry={nodes.Animals_Icon.geometry} material={materials.Icons} position={[0, 0, -0.018]} />
            </skinnedMesh>
          </group>
        </group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={34.114} position={[0.759, 18.647, 15.557]} rotation={[-0.2, 0, 0]} scale={5.334} />
        <mesh name="Annelids" geometry={nodes.Annelids.geometry} material={materials['Material.005']} position={[0.274, -15.046, 9.474]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Annelids_Icon" geometry={nodes.Annelids_Icon.geometry} material={materials.Icons} position={[-0.019, 0.324, 0.011]} scale={-0.665} />
        </mesh>
        <mesh name="Cnidarians" geometry={nodes.Cnidarians.geometry} material={materials['Material.002']} position={[0.347, -14.832, 9.507]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Cnidarians_Icon" geometry={nodes.Cnidarians_Icon.geometry} material={materials.Icons} position={[-0.005, 0.256, -0.003]} scale={0.747} />
        </mesh>
        <mesh name="Fish" geometry={nodes.Fish.geometry} material={materials['Material.001']} position={[0.316, -15.151, 9.493]} rotation={[0, 1.141, Math.PI / 2]}>
          <mesh name="Fish_Icon" geometry={nodes.Fish_Icon.geometry} material={materials.Icons} position={[0.035, 0.464, -0.004]} rotation={[0, -Math.PI / 2, 0]} scale={0.705} />
        </mesh>
        <mesh name="Humans" geometry={nodes.Humans.geometry} material={materials['Material.003']} position={[0.194, -15.072, 9.418]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Humans_Icon" geometry={nodes.Humans_Icon.geometry} material={materials.Icons} position={[-0.022, 0.209, -0.012]} scale={0.715} />
        </mesh>
        <mesh name="Livestock" geometry={nodes.Livestock.geometry} material={materials['Material.003']} position={[0.61, -15.106, 9.609]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Livestock_Icon" geometry={nodes.Livestock_Icon.geometry} material={materials.Icons} position={[-0.033, 0.238, -0.012]} scale={0.744} />
        </mesh>
        <mesh name="Mollusks" geometry={nodes.Mollusks.geometry} material={materials['Material.001']} position={[0.279, -15.157, 9.458]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Mollusks_Icon" geometry={nodes.Mollusks_Icon.geometry} material={materials.Icons} position={[0.004, 0.326, -0.013]} scale={0.748} />
        </mesh>
        <mesh name="Nematodes" geometry={nodes.Nematodes.geometry} material={materials['Material.005']} position={[0.473, -15.276, 9.186]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Nematodes_Icon" geometry={nodes.Nematodes_Icon.geometry} material={materials.Icons} position={[-0.002, 0.149, -0.01]} scale={0.415} />
        </mesh>
        <mesh name="Wild_Birds" geometry={nodes.Wild_Birds.geometry} material={materials['Material.003']} position={[0.288, -14.902, 9.462]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Wild_Birds_Icon" geometry={nodes.Wild_Birds_Icon.geometry} material={materials.Icons} position={[0, 0.077, 0]} scale={0.225} />
        </mesh>
        <mesh name="Wild_Mammals" geometry={nodes.Wild_Mammals.geometry} material={materials['Material.003']} position={[0.057, -15.081, 9.357]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Wild_Mammals_Icon" geometry={nodes.Wild_Mammals_Icon.geometry} material={materials.Icons} position={[0.001, 0.111, -0.007]} scale={0.228} />
        </mesh>
        <mesh name="Archaea" geometry={nodes.Archaea.geometry} material={materials.Bacteria} position={[6.418, -6.594, 33.375]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Archaea_Icon" geometry={nodes.Archaea_Icon.geometry} material={materials.Icons} position={[0.045, 0.981, -0.054]} rotation={[0, 0, -0.006]} scale={0.818} />
        </mesh>
        <mesh name="Bacteria" geometry={nodes.Bacteria.geometry} material={materials.Bacteria} position={[4.63, -5.461, 29.838]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Bacteria_Icon" geometry={nodes.Bacteria_Icon.geometry} material={materials.Icons} position={[-0.025, 2.098, 0.093]} rotation={[-Math.PI, 0, 0]} scale={-0.947} />
        </mesh>
        <mesh name="Fungi" geometry={nodes.Fungi.geometry} material={materials.Fungi} position={[-0.72, -6.405, 33.314]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Fungi_Icon" geometry={nodes.Fungi_Icon.geometry} material={materials.Icons} position={[0.031, 1.157, -0.019]} rotation={[0, Math.PI / 2, 0]} scale={0.639} />
        </mesh>
        <mesh name="Protists" geometry={nodes.Protists.geometry} material={materials.Bacteria} position={[7.858, -6.767, 35.189]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Protists_Icon" geometry={nodes.Protists_Icon.geometry} material={materials.Icons} position={[-0.055, 0.806, 0.018]} rotation={[0, Math.PI / 2, 0]} scale={0.687} />
        </mesh>
        <mesh name="Plants" geometry={nodes.Plants.geometry} material={materials.Plants} position={[-4.044, -3.783, 27.872]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={3.358}>
          <mesh name="Plants_Icon" geometry={nodes.Plants_Icon.geometry} material={materials.Icons} position={[-0.037, 1.179, -0.005]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
        </mesh>
        <mesh name="Marine_Arthropods" geometry={nodes.Marine_Arthropods.geometry} material={materials['Material.002']} position={[0.383, -15.091, 9.494]} rotation={[Math.PI / 2, 0, 0.43]} scale={1.073}>
          <mesh name="Marine_Arthropods_Icon" geometry={nodes.Marine_Arthropods_Icon.geometry} material={materials.Icons} position={[-0.024, 0.459, -0.004]} scale={[0.801, 0.893, 0.801]} />
        </mesh>
        <mesh name="Virus" geometry={nodes.Virus.geometry} material={materials.Material} position={[14.996, 1.342, 2.444]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Virus_Icon" geometry={nodes.Virus_Icon.geometry} material={materials.Icons} position={[-0.006, 0.307, -0.001]} scale={0.217} />
        </mesh>
        <mesh name="Arthropods" geometry={nodes.Arthropods.geometry} material={materials['Material.005']} position={[0.492, -15.229, 9.574]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Arthropods_Icon" geometry={nodes.Arthropods_Icon.geometry} material={materials.Icons} position={[-0.002, 0.312, 0.012]} scale={0.722} />
        </mesh>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Rollout} position={[0.976, -2.488, 9.278]} rotation={[Math.PI / 2, 0, 0]} scale={[0.009, 0.723, 0.075]} />
        <mesh name="LUCA" geometry={nodes.LUCA.geometry} material={materials['Material.004']} position={[1.833, -7.415, 35.759]} scale={0.509}>
          <mesh name="LUCA_Icon" geometry={nodes.LUCA_Icon.geometry} material={materials.Icons} position={[-0.008, -0.019, 1.063]} rotation={[Math.PI / 2, 0, 0]} scale={0.561} />
        </mesh>
        <mesh name="Globe" geometry={nodes.Globe.geometry} material={materials.Material_Test} position={[0.676, 15.606, 0]} rotation={[1.964, -0.055, 0.023]} scale={9.468} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Tree} position={[1.247, -4.049, 1.436]} rotation={[Math.PI / 2, 0, 0]} scale={[6.678, 3.04, 3.047]} />
        <mesh name="Cars" geometry={nodes.Cars.geometry} material={materials['Material.006']} position={[21.079, 1.604, 0.308]} rotation={[-Math.PI, 0.317, -Math.PI]} scale={1.22}>
          <mesh name="Cars_Icon" geometry={nodes.Cars_Icon.geometry} material={materials['Material.008']} position={[0.038, -0.022, 0.519]} rotation={[Math.PI / 2, 0, 0]} scale={1.629} />
        </mesh>
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[0.135, 1.019, 0.359]} scale={145.642} />
        <mesh name="Concrete" geometry={nodes.Concrete.geometry} material={materials.Concrete} morphTargetDictionary={nodes.Concrete.morphTargetDictionary} morphTargetInfluences={nodes.Concrete.morphTargetInfluences} position={[95.607, -2.192, -5.909]} rotation={[0, -0.902, 0]} scale={6.499}>
          <mesh name="Concrete_Icon" geometry={nodes.Concrete_Icon.geometry} material={materials['Material.008']} position={[0.001, -0.007, 0.515]} rotation={[Math.PI / 2, 0, 0]} scale={0.611} />
        </mesh>
        <mesh name="Bricks" geometry={nodes.Bricks.geometry} material={materials.Bricks} morphTargetDictionary={nodes.Bricks.morphTargetDictionary} morphTargetInfluences={nodes.Bricks.morphTargetInfluences} position={[85.355, -0.829, 1.487]} rotation={[0, Math.PI / 6, 0]} scale={3.583}>
          <mesh name="Bricks_Icon" geometry={nodes.Bricks_Icon.geometry} material={materials['Material.008']} position={[-0.006, -0.008, 0.537]} rotation={[Math.PI / 2, 0, 0]} scale={1.128} />
        </mesh>
        <mesh name="Metals" geometry={nodes.Metals.geometry} material={materials.Metal} morphTargetDictionary={nodes.Metals.morphTargetDictionary} morphTargetInfluences={nodes.Metals.morphTargetInfluences} position={[79.198, -0.257, 5.488]} rotation={[0, 0.743, 0]} scale={[2.692, 2.555, 2.555]}>
          <mesh name="Metals_Icon" geometry={nodes.Metals_Icon.geometry} material={materials['Material.008']} position={[0.002, 0.023, 0.519]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.46, 0.541, 0.485]} />
        </mesh>
        <mesh name="Aggregates" geometry={nodes.Aggregates.geometry} material={materials.Aggregates} morphTargetDictionary={nodes.Aggregates.morphTargetDictionary} morphTargetInfluences={nodes.Aggregates.morphTargetInfluences} position={[89.707, -1.84, -2.124]} rotation={[0, -0.265, 0]} scale={5.779}>
          <mesh name="Aggregates_Icon" geometry={nodes.Aggregates_Icon.geometry} material={materials['Material.008']} position={[0.016, 0.027, 0.546]} rotation={[Math.PI / 2, 0, 0]} scale={0.941} />
        </mesh>
        <mesh name="Asphalt" geometry={nodes.Asphalt.geometry} material={materials.Asphalt} morphTargetDictionary={nodes.Asphalt.morphTargetDictionary} morphTargetInfluences={nodes.Asphalt.morphTargetInfluences} position={[81.98, -0.579, 3.641]} rotation={[0, Math.PI / 6, 0]} scale={3.191}>
          <mesh name="Asphalt_Icon" geometry={nodes.Asphalt_Icon.geometry} material={materials['Material.008']} position={[-0.003, 0.016, 0.581]} rotation={[Math.PI / 2, 0, 0]} scale={1.102} />
        </mesh>
        <mesh name="Plastics" geometry={nodes.Plastics.geometry} material={materials.Plastics} morphTargetDictionary={nodes.Plastics.morphTargetDictionary} morphTargetInfluences={nodes.Plastics.morphTargetInfluences} position={[77.371, 0.193, 7.08]} rotation={[0, 1.288, 0]} scale={1.623}>
          <mesh name="Plastics_Icon" geometry={nodes.Plastics_Icon.geometry} material={materials['Material.008']} position={[-0.004, -0.007, 0.504]} rotation={[Math.PI / 2, 0, 0]} scale={[0.656, 0.732, 0.787]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Camera.glb')
