/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 .\\public\\globe.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/globe.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Globe001" geometry={nodes.Globe001.geometry} material={materials.Globe2} position={[0, 15.606, 0]} rotation={[1.964, -0.055, 0.023]} scale={9.468} />
      </group>
    </group>
  )
}

useGLTF.preload('/globe.glb')
