/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/Part01.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Part01.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Annelids" geometry={nodes.Annelids.geometry} material={materials['Material.005']} position={[0.274, -15.046, 9.474]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Annelids_Icon" geometry={nodes.Annelids_Icon.geometry} material={materials.Icons} position={[-0.019, 0.324, 0.011]} scale={-0.665} />
        </mesh>
        <mesh name="Cnidarians" geometry={nodes.Cnidarians.geometry} material={materials['Material.002']} position={[0.347, -14.832, 9.507]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Cnidarians_Icon" geometry={nodes.Cnidarians_Icon.geometry} material={materials.Icons} position={[-0.005, 0.256, -0.003]} scale={0.747} />
        </mesh>
        <mesh name="Fish" geometry={nodes.Fish.geometry} material={materials['Material.001']} position={[0.316, -15.151, 9.493]} rotation={[0, 1.141, Math.PI / 2]}>
          <mesh name="Fish_Icon" geometry={nodes.Fish_Icon.geometry} material={materials.Icons} position={[0.035, 0.464, -0.004]} rotation={[0, -Math.PI / 2, 0]} scale={0.705} />
        </mesh>
        <mesh name="Humans" geometry={nodes.Humans.geometry} material={materials['Material.003']} position={[0.194, -15.072, 9.418]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Humans_Icon" geometry={nodes.Humans_Icon.geometry} material={materials.Icons} position={[-0.022, 0.209, -0.012]} scale={0.715} />
        </mesh>
        <mesh name="Livestock" geometry={nodes.Livestock.geometry} material={materials['Material.003']} position={[0.61, -15.106, 9.609]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Livestock_Icon" geometry={nodes.Livestock_Icon.geometry} material={materials.Icons} position={[-0.033, 0.238, -0.012]} scale={0.744} />
        </mesh>
        <mesh name="Mollusks" geometry={nodes.Mollusks.geometry} material={materials['Material.001']} position={[0.279, -15.157, 9.458]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Mollusks_Icon" geometry={nodes.Mollusks_Icon.geometry} material={materials.Icons} position={[0.004, 0.326, -0.013]} scale={0.748} />
        </mesh>
        <mesh name="Nematodes" geometry={nodes.Nematodes.geometry} material={materials['Material.005']} position={[0.473, -15.276, 9.186]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Nematodes_Icon" geometry={nodes.Nematodes_Icon.geometry} material={materials.Icons} position={[-0.002, 0.149, -0.01]} scale={0.415} />
        </mesh>
        <mesh name="Wild_Birds" geometry={nodes.Wild_Birds.geometry} material={materials['Material.003']} position={[0.288, -14.902, 9.462]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Wild_Birds_Icon" geometry={nodes.Wild_Birds_Icon.geometry} material={materials.Icons} position={[0, 0.077, 0]} scale={0.225} />
        </mesh>
        <mesh name="Wild_Mammals" geometry={nodes.Wild_Mammals.geometry} material={materials['Material.003']} position={[0.057, -15.081, 9.357]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Wild_Mammals_Icon" geometry={nodes.Wild_Mammals_Icon.geometry} material={materials.Icons} position={[0.001, 0.111, -0.007]} scale={0.228} />
        </mesh>
        <mesh name="Archaea" geometry={nodes.Archaea.geometry} material={materials.Bacteria} position={[6.418, -6.594, -1.012]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Archaea_Icon" geometry={nodes.Archaea_Icon.geometry} material={materials.Icons} position={[0.045, 0.981, -0.054]} rotation={[0, 0, -0.006]} scale={0.818} />
        </mesh>
        <mesh name="Bacteria" geometry={nodes.Bacteria.geometry} material={materials.Bacteria} position={[4.63, -5.461, -4.55]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Bacteria_Icon" geometry={nodes.Bacteria_Icon.geometry} material={materials.Icons} position={[-0.025, 2.098, 0.093]} scale={0.947} />
        </mesh>
        <mesh name="Fungi" geometry={nodes.Fungi.geometry} material={materials.Fungi} position={[-0.72, -6.405, -1.073]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Fungi_Icon" geometry={nodes.Fungi_Icon.geometry} material={materials.Icons} position={[0.031, 1.157, -0.019]} rotation={[0, Math.PI / 2, 0]} scale={0.639} />
        </mesh>
        <mesh name="Protists" geometry={nodes.Protists.geometry} material={materials.Bacteria} position={[7.858, -6.767, 0.802]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Protists_Icon" geometry={nodes.Protists_Icon.geometry} material={materials.Icons} position={[-0.055, 0.806, 0.018]} rotation={[0, Math.PI / 2, 0]} scale={0.687} />
        </mesh>
        <mesh name="Plants" geometry={nodes.Plants.geometry} material={materials.Plants} position={[-4.044, -3.783, -6.515]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={3.358}>
          <mesh name="Plants_Icon" geometry={nodes.Plants_Icon.geometry} material={materials.Icons} position={[-0.037, 1.179, -0.005]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
        </mesh>
        <mesh name="Animals" geometry={nodes.Animals.geometry} material={materials.Animals} position={[0.726, 1.751, 0.96]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.629}>
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-1.103, 0.003, 0.967]} rotation={[Math.PI, 0, 1.57]} scale={[1.037, 0.016, 0.493]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-1.117, 0.003, -1.005]} rotation={[0, 0, -1.57]} scale={[0.998, 0.016, 0.493]} />
          <mesh name="Animals_Icon" geometry={nodes.Animals_Icon.geometry} material={materials.Icons} position={[-0.033, 1.192, -0.03]} rotation={[0, Math.PI / 2, 0]} scale={[1.141, 0.471, 0.256]} />
        </mesh>
        <mesh name="Marine_Arthropods" geometry={nodes.Marine_Arthropods.geometry} material={materials['Material.002']} position={[0.383, -15.091, 9.494]} rotation={[Math.PI / 2, 0, 0.43]} scale={1.073}>
          <mesh name="Marine_Arthropods_Icon" geometry={nodes.Marine_Arthropods_Icon.geometry} material={materials.Icons} position={[-0.024, 0.459, -0.004]} scale={[0.801, 0.893, 0.801]} />
        </mesh>
        <mesh name="Virus" geometry={nodes.Virus.geometry} material={materials.Material} position={[14.996, 1.342, 2.444]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Virus_Icon" geometry={nodes.Virus_Icon.geometry} material={materials.Icons} position={[-0.006, 0.307, -0.001]} scale={0.217} />
        </mesh>
        <mesh name="Arthropods" geometry={nodes.Arthropods.geometry} material={materials['Material.005']} position={[0.492, -15.229, 9.574]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Arthropods_Icon" geometry={nodes.Arthropods_Icon.geometry} material={materials.Icons} position={[-0.002, 0.312, 0.012]} scale={0.722} />
        </mesh>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Rollout} position={[0.976, -2.488, 9.278]} rotation={[Math.PI / 2, 0, 0]} scale={[0.009, 0.723, 0.075]} />
        <mesh name="LUCA" geometry={nodes.LUCA.geometry} material={materials['Material.004']} position={[1.833, -7.415, 1.372]} scale={0.509}>
          <mesh name="LUCA_Icon" geometry={nodes.LUCA_Icon.geometry} material={materials.Icons} position={[-0.008, -0.019, 1.063]} rotation={[Math.PI / 2, 0, 0]} scale={0.561} />
        </mesh>
        <mesh name="Globe" geometry={nodes.Globe.geometry} material={materials.Material_Test} position={[0.676, 15.606, 0]} rotation={[1.964, -0.055, 0.023]} scale={9.468} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Tree} position={[1.247, -4.049, 1.436]} rotation={[Math.PI / 2, 0, 0]} scale={[6.678, 3.04, 3.047]} />
        <mesh name="Concrete" geometry={nodes.Concrete.geometry} material={materials.Concrete} position={[72.629, -2.192, -16.763]} rotation={[0, Math.PI / 6, 0]} scale={6.499}>
          <mesh name="Concrete_Icon" geometry={nodes.Concrete_Icon.geometry} material={materials['Material.008']} position={[0.001, -0.007, 0.515]} rotation={[Math.PI / 2, 0, 0]} scale={0.66} />
        </mesh>
        <mesh name="Bricks" geometry={nodes.Bricks.geometry} material={materials.Bricks} position={[58.449, -0.829, -6.55]} rotation={[0, Math.PI / 6, 0]} scale={3.583}>
          <mesh name="Bricks_Icon" geometry={nodes.Bricks_Icon.geometry} material={materials['Material.008']} position={[-0.006, -0.008, 0.537]} rotation={[Math.PI / 2, 0, 0]} scale={1.196} />
        </mesh>
        <mesh name="Waste" geometry={nodes.Waste.geometry} material={materials.Waste} position={[-35.283, -5.007, 118.626]} rotation={[0, -Math.PI / 2, 0]} scale={6.472} />
        <mesh name="Cars" geometry={nodes.Cars.geometry} material={materials['Material.006']} position={[36.118, 1.604, -2.979]} rotation={[Math.PI, -0.248, Math.PI]} scale={1.22}>
          <mesh name="Cars_Icon" geometry={nodes.Cars_Icon.geometry} material={materials['Material.008']} position={[0.038, -0.022, 0.519]} rotation={[Math.PI / 2, 0, 0]} scale={1.86} />
        </mesh>
        <mesh name="Metals" geometry={nodes.Metals.geometry} material={materials.Metal} position={[49.202, -0.257, -4.48]} rotation={[0, Math.PI / 6, 0]} scale={[2.692, 2.555, 2.555]}>
          <mesh name="Metals_Icon" geometry={nodes.Metals_Icon.geometry} material={materials['Material.008']} position={[0.002, 0.023, 0.519]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.678, 0.796, 0.714]} />
        </mesh>
        <mesh name="Coal" geometry={nodes.Coal.geometry} material={materials.Coal} position={[-34.191, -7.262, 131.125]} rotation={[0, -Math.PI / 2, 0]} scale={9.788} />
        <mesh name="Yearly_Coal" geometry={nodes.Yearly_Coal.geometry} material={materials.Coal} position={[-40.517, 1.055, 131.125]} rotation={[0, -Math.PI / 2, 0]} scale={1.981} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[0.135, 1.019, 0.359]} scale={145.642} />
        <mesh name="Aggregates" geometry={nodes.Aggregates.geometry} material={materials.Aggregates} position={[64.25, -1.84, -11.547]} rotation={[0, Math.PI / 6, 0]} scale={5.779}>
          <mesh name="Aggregates_Icon" geometry={nodes.Aggregates_Icon.geometry} material={materials['Material.008']} position={[0.016, 0.027, 0.546]} rotation={[Math.PI / 2, 0, 0]} scale={1.191} />
        </mesh>
        <mesh name="Asphalt" geometry={nodes.Asphalt.geometry} material={materials.Asphalt} position={[56.042, -0.579, -6.328]} rotation={[0, Math.PI / 6, 0]} scale={3.191}>
          <mesh name="Asphalt_Icon" geometry={nodes.Asphalt_Icon.geometry} material={materials['Material.008']} position={[-0.003, 0.016, 0.581]} rotation={[Math.PI / 2, 0, 0]} scale={1.217} />
        </mesh>
        <mesh name="Plastics" geometry={nodes.Plastics.geometry} material={materials.Plastics} position={[-1.512, 0.193, 7.08]} rotation={[0, Math.PI / 6, 0]} scale={1.623}>
          <mesh name="Plastics_Icon" geometry={nodes.Plastics_Icon.geometry} material={materials['Material.008']} position={[-0.004, -0.007, 0.504]} rotation={[Math.PI / 2, 0, 0]} scale={[0.851, 0.949, 1.021]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Part01.glb')
