/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/Part_01.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Part_01.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Annelids" geometry={nodes.Annelids.geometry} material={materials['Material.005']} position={[0.27, -15.05, 9.47]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_7@3x" geometry={nodes['Artboard_4_copy_7@3x'].geometry} material={materials.Icons} position={[-0.02, 0.32, 0.01]} scale={-0.66} />
        </mesh>
        <mesh name="Cnidarians" geometry={nodes.Cnidarians.geometry} material={materials['Material.002']} position={[0.35, -14.83, 9.51]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_15@3x" geometry={nodes['Artboard_4_copy_15@3x'].geometry} material={materials.Icons} position={[-0.01, 0.26, 0]} scale={0.75} />
        </mesh>
        <mesh name="Fish" geometry={nodes.Fish.geometry} material={materials['Material.001']} position={[0.32, -15.15, 9.49]} rotation={[0, 1.14, Math.PI / 2]}>
          <mesh name="Artboard_4_copy_5@3x001" geometry={nodes['Artboard_4_copy_5@3x001'].geometry} material={materials.Icons} position={[0.03, 0.46, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.7} />
        </mesh>
        <mesh name="Humans" geometry={nodes.Humans.geometry} material={materials['Material.003']} position={[0.19, -15.07, 9.42]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_10@3x" geometry={nodes['Artboard_4_copy_10@3x'].geometry} material={materials.Icons} position={[-0.02, 0.21, -0.01]} scale={0.71} />
        </mesh>
        <mesh name="Livestock" geometry={nodes.Livestock.geometry} material={materials['Material.003']} position={[0.61, -15.11, 9.61]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_11@3x" geometry={nodes['Artboard_4_copy_11@3x'].geometry} material={materials.Icons} position={[-0.03, 0.24, -0.01]} scale={0.74} />
        </mesh>
        <mesh name="Mollusks" geometry={nodes.Mollusks.geometry} material={materials['Material.001']} position={[0.28, -15.16, 9.46]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_14@3x" geometry={nodes['Artboard_4_copy_14@3x'].geometry} material={materials.Icons} position={[0, 0.33, -0.01]} scale={0.75} />
        </mesh>
        <mesh name="Nematodes" geometry={nodes.Nematodes.geometry} material={materials['Material.005']} position={[0.47, -15.28, 9.19]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_9@3x001" geometry={nodes['Artboard_4_copy_9@3x001'].geometry} material={materials.Icons} position={[0, 0.15, -0.01]} scale={0.42} />
        </mesh>
        <mesh name="Wild_Birds" geometry={nodes.Wild_Birds.geometry} material={materials['Material.003']} position={[0.29, -14.9, 9.46]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_13@3x001" geometry={nodes['Artboard_4_copy_13@3x001'].geometry} material={materials.Icons} position={[0, 0.08, 0]} scale={0.22} />
        </mesh>
        <mesh name="Wild_Mammals" geometry={nodes.Wild_Mammals.geometry} material={materials['Material.003']} position={[0.06, -15.08, 9.36]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_12@3x001" geometry={nodes['Artboard_4_copy_12@3x001'].geometry} material={materials.Icons} position={[0, 0.11, -0.01]} scale={0.23} />
        </mesh>
        <mesh name="Archaea" geometry={nodes.Archaea.geometry} material={materials.Bacteria} position={[6.42, -6.59, -1.01]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Artboard_4_copy_2@3x" geometry={nodes['Artboard_4_copy_2@3x'].geometry} material={materials.Icons} position={[0.05, 0.98, -0.05]} rotation={[0, 0, -0.01]} scale={0.82} />
        </mesh>
        <mesh name="Bacteria" geometry={nodes.Bacteria.geometry} material={materials.Bacteria} position={[4.63, -5.46, -4.55]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Artboard_4@3x" geometry={nodes['Artboard_4@3x'].geometry} material={materials.Icons} position={[-0.02, 2.1, 0.09]} scale={0.95} />
        </mesh>
        <mesh name="Fungi" geometry={nodes.Fungi.geometry} material={materials.Fungi} position={[-0.72, -6.4, -1.07]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Artboard_4_copy_4@3x001" geometry={nodes['Artboard_4_copy_4@3x001'].geometry} material={materials.Icons} position={[0.03, 1.16, -0.02]} rotation={[0, Math.PI / 2, 0]} scale={0.64} />
        </mesh>
        <mesh name="Protists" geometry={nodes.Protists.geometry} material={materials.Bacteria} position={[7.86, -6.77, 0.8]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Artboard_4_copy_3@3x" geometry={nodes['Artboard_4_copy_3@3x'].geometry} material={materials.Icons} position={[-0.06, 0.81, 0.02]} rotation={[0, Math.PI / 2, 0]} scale={0.69} />
        </mesh>
        <mesh name="Plants" geometry={nodes.Plants.geometry} material={materials.Plants} position={[-4.04, -3.78, -6.51]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={3.36}>
          <mesh name="Artboard_4_copy@3x" geometry={nodes['Artboard_4_copy@3x'].geometry} material={materials.Icons} position={[-0.04, 1.18, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
        </mesh>
        <mesh name="Animals" geometry={nodes.Animals.geometry} material={materials.Animals} position={[0.73, 1.75, 0.96]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.63}>
          <mesh name="Artboard_4_copy_4@3x002" geometry={nodes['Artboard_4_copy_4@3x002'].geometry} material={materials.Icons} position={[-0.03, 1.19, -0.03]} rotation={[0, Math.PI / 2, 0]} scale={[1.78, 0.73, 0.44]} />
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-1.08, -1.01, 0.02]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[1.03, 0.02, 0.57]} />
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-1.06, 1.08, 0.02]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.05, 0.02, 0.56]} />
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-1.1, 0, 0.97]} rotation={[Math.PI, 0, 1.57]} scale={[1.04, 0.02, 0.49]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-1.12, 0, -1.01]} rotation={[0, 0, -1.57]} scale={[1, 0.02, 0.49]} />
        </mesh>
        <mesh name="Marine_Arthropods" geometry={nodes.Marine_Arthropods.geometry} material={materials['Material.002']} position={[0.38, -15.09, 9.49]} rotation={[Math.PI / 2, 0, 0.43]} scale={1.07}>
          <mesh name="Artboard_4_copy_6@3x" geometry={nodes['Artboard_4_copy_6@3x'].geometry} material={materials.Icons} position={[-0.02, 0.46, 0]} scale={[0.8, 0.89, 0.8]} />
        </mesh>
        <mesh name="Virus" geometry={nodes.Virus.geometry} material={materials.Material} position={[15, 1.34, 2.44]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.Icons} position={[-0.01, 0.31, 0]} scale={0.22} />
        </mesh>
        <mesh name="Arthropods" geometry={nodes.Arthropods.geometry} material={materials['Material.005']} position={[0.49, -15.23, 9.57]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Artboard_4_copy_8@3x" geometry={nodes['Artboard_4_copy_8@3x'].geometry} material={materials.Icons} position={[0, 0.31, 0.01]} scale={0.72} />
        </mesh>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Rollout} position={[0.98, -2.49, 9.28]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.72, 0.08]} />
        <mesh name="LUCA" geometry={nodes.LUCA.geometry} material={materials['Material.004']} position={[1.83, -7.41, 1.37]} scale={0.51}>
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Icons} position={[-0.01, -0.02, 1.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.56} />
        </mesh>
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Tree} position={[1.25, -4.05, 1.44]} rotation={[Math.PI / 2, 0, 0]} scale={[6.68, 3.04, 3.05]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Part_01.glb')
