/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Part01.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Part01.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[93.05, 0.683, 1.008]} scale={1.086}>
          <group name="Armature" position={[0, -1.057, 0]} scale={0.921}>
            <primitive object={nodes.Bone} />
            <primitive object={nodes.Bone001} />
            <primitive object={nodes.neutral_bone} />
            <skinnedMesh name="Animals" geometry={nodes.Animals.geometry} material={materials.Animals} skeleton={nodes.Animals.skeleton} />
          </group>
          <mesh name="Animals_Text" geometry={nodes.Animals_Text.geometry} material={materials.Icons} position={[0.525, -0.595, 0.709]} rotation={[Math.PI / 2, 0, 0]} scale={0.921} />
        </group>
        <group name="Year" position={[0, 36.925, -5.872]} rotation={[0, Math.PI / 6, 0]} scale={1.711} />
        <group name="2023" position={[4.045, -7.892, 13.634]} scale={0.177}>
          <mesh name="2023_Text" geometry={nodes['2023_Text'].geometry} material={materials.Icons} position={[-1.011, -0.518, 0.679]} rotation={[Math.PI / 2, 0, -Math.PI / 6]} scale={0.832} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Blak} position={[2.284, 0.005, -1.01]} rotation={[Math.PI / 2, 0, 2.653]} scale={[-1.829, -1.937, -0.047]} />
        </group>
        <group name="1990" position={[4.045, -9.184, 13.634]} scale={0.177}>
          <mesh name="1990_Text" geometry={nodes['1990_Text'].geometry} material={materials.Icons} position={[-1.011, 0.369, 0.679]} rotation={[Math.PI / 2, 0, -Math.PI / 6]} scale={0.832} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.Blak} position={[2.284, 0.005, -1.01]} rotation={[Math.PI / 2, 0, 2.653]} scale={[-1.901, -2.014, -0.049]} />
        </group>
        <group name="1900" position={[4.045, -9.396, 13.622]} scale={0.177}>
          <mesh name="1900_Text" geometry={nodes['1900_Text'].geometry} material={materials.Icons} position={[-1.011, 0.32, 0.679]} rotation={[Math.PI / 2, 0, -Math.PI / 6]} scale={0.832} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.Blak} position={[2.284, 0.005, -1.01]} rotation={[Math.PI / 2, 0, 2.653]} scale={[-1.829, -1.937, -0.047]} />
        </group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={6.972} position={[20.924, 10.746, 75.786]} rotation={[-0.075, 0.252, 0.019]} scale={5.334} />
        <mesh name="Annelids" geometry={nodes.Annelids.geometry} material={materials['Material.005']} position={[0.274, -15.046, 9.474]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Annelids_Icon" geometry={nodes.Annelids_Icon.geometry} material={materials.Icons} position={[-0.019, 0.324, 0.011]} scale={-0.665} />
        </mesh>
        <mesh name="Cnidarians" geometry={nodes.Cnidarians.geometry} material={materials['Material.002']} position={[0.347, -14.832, 9.507]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Cnidarians_Icon" geometry={nodes.Cnidarians_Icon.geometry} material={materials.Icons} position={[-0.012, 0.264, 0.012]} scale={0.729} />
        </mesh>
        <mesh name="Fish" geometry={nodes.Fish.geometry} material={materials['Material.001']} position={[0.316, -15.151, 9.493]} rotation={[0, 1.141, Math.PI / 2]}>
          <mesh name="Fish_Icon" geometry={nodes.Fish_Icon.geometry} material={materials.Icons} position={[0.006, 0.464, -0.004]} rotation={[0, -Math.PI / 2, 0]} scale={0.705} />
        </mesh>
        <mesh name="Livestock" geometry={nodes.Livestock.geometry} material={materials['Material.003']} position={[0.61, -15.106, 9.609]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Livestock_Icon" geometry={nodes.Livestock_Icon.geometry} material={materials.Icons} position={[-0.023, 0.238, -0.017]} scale={0.72} />
        </mesh>
        <mesh name="Mollusks" geometry={nodes.Mollusks.geometry} material={materials['Material.001']} position={[0.279, -15.157, 9.458]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Mollusks_Icon" geometry={nodes.Mollusks_Icon.geometry} material={materials.Icons} position={[0.004, 0.326, -0.013]} scale={0.748} />
        </mesh>
        <mesh name="Nematodes" geometry={nodes.Nematodes.geometry} material={materials['Material.005']} position={[0.473, -15.276, 9.186]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Nematodes_Icon" geometry={nodes.Nematodes_Icon.geometry} material={materials.Icons} position={[0.015, 0.149, -0.01]} scale={0.4} />
        </mesh>
        <mesh name="Wild_Birds" geometry={nodes.Wild_Birds.geometry} material={materials['Material.003']} position={[0.288, -14.902, 9.462]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Wild_Birds_Icon" geometry={nodes.Wild_Birds_Icon.geometry} material={materials.Icons} position={[0, 0.077, 0]} scale={0.225} />
        </mesh>
        <mesh name="Wild_Mammals" geometry={nodes.Wild_Mammals.geometry} material={materials['Material.003']} position={[0.057, -15.081, 9.357]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Wild_Mammals_Icon" geometry={nodes.Wild_Mammals_Icon.geometry} material={materials.Icons} position={[0.001, 0.111, -0.007]} scale={0.228} />
        </mesh>
        <mesh name="Archaea" geometry={nodes.Archaea.geometry} material={materials.Archaea} position={[98.726, 0.031, -1.012]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Archaea_Text" geometry={nodes.Archaea_Text.geometry} material={materials.Icons} position={[0.426, 1.016, -0.084]} />
          <mesh name="Archaea_Icon" geometry={nodes.Archaea_Icon.geometry} material={materials.Icons} position={[0.003, 0.981, -0.105]} rotation={[0, 0, -0.006]} scale={0.679} />
        </mesh>
        <mesh name="Bacteria" geometry={nodes.Bacteria.geometry} material={materials.Bacteria} position={[96.938, -1.19, -4.55]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Bacteria_Icon" geometry={nodes.Bacteria_Icon.geometry} material={materials.Icons} position={[-0.025, 2.098, 0.093]} scale={0.739} />
          <mesh name="Bacteria_Text" geometry={nodes.Bacteria_Text.geometry} material={materials.Icons} position={[0.482, 2.18, 0.624]} />
        </mesh>
        <mesh name="Fungi" geometry={nodes.Fungi.geometry} material={materials.Fungi} position={[91.587, -0.157, -1.073]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Fungi_Icon" geometry={nodes.Fungi_Icon.geometry} material={materials.Icons} position={[0.031, 1.157, 0.007]} rotation={[0, Math.PI / 2, 0]} scale={0.639} />
          <mesh name="Fungi_Text" geometry={nodes.Fungi_Text.geometry} material={materials.Icons} position={[0.928, 1.154, -0.509]} rotation={[0, Math.PI / 2, 0]} scale={0.884} />
        </mesh>
        <mesh name="Protists" geometry={nodes.Protists.geometry} material={materials.Protists} position={[100.165, 0.147, 0.802]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh name="Protists_Icon" geometry={nodes.Protists_Icon.geometry} material={materials.Icons} position={[-0.092, 0.806, 0.018]} rotation={[0, Math.PI / 2, 0]} scale={0.629} />
          <mesh name="Protists_Text" geometry={nodes.Protists_Text.geometry} material={materials.Icons} position={[0.138, 0.843, -0.545]} rotation={[0, Math.PI / 2, 0]} />
        </mesh>
        <mesh name="Plants" geometry={nodes.Plants.geometry} material={materials.Plants} position={[88.264, -2.909, -6.515]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={3.358}>
          <mesh name="Plants_Icon" geometry={nodes.Plants_Icon.geometry} material={materials.Icons} position={[-0.037, 1.179, -0.005]} rotation={[0, Math.PI / 2, 0]} scale={0.232} />
          <mesh name="Plants_Text" geometry={nodes.Plants_Text.geometry} material={materials.Icons} position={[0.349, 1.147, -0.15]} rotation={[0, Math.PI / 2, 0]} scale={0.298} />
        </mesh>
        <mesh name="Marine_Arthropods" geometry={nodes.Marine_Arthropods.geometry} material={materials['Material.002']} position={[0.383, -15.091, 9.494]} rotation={[Math.PI / 2, 0, 0.43]} scale={1.073}>
          <mesh name="Marine_Arthropods_Icon" geometry={nodes.Marine_Arthropods_Icon.geometry} material={materials.Icons} position={[-0.024, 0.459, -0.004]} scale={[0.801, 0.893, 0.801]} />
        </mesh>
        <mesh name="Viruses" geometry={nodes.Viruses.geometry} material={materials.Material} position={[14.996, 1.302, 2.444]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Viruses_Icon" geometry={nodes.Viruses_Icon.geometry} material={materials.Icons} position={[-0.006, 0.307, -0.001]} scale={0.217} />
        </mesh>
        <mesh name="Arthropods" geometry={nodes.Arthropods.geometry} material={materials['Material.005']} position={[0.492, -15.229, 9.574]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Arthropods_Icon" geometry={nodes.Arthropods_Icon.geometry} material={materials.Icons} position={[-0.002, 0.312, 0.012]} scale={0.629} />
        </mesh>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Rollout} position={[0.059, -9.395, 9.278]} rotation={[Math.PI / 2, 0, 0]} scale={[0.049, 0.122, 0.041]} />
        <mesh name="LUCA" geometry={nodes.LUCA.geometry} material={materials['Material.004']} position={[1.833, -5.192, 1.372]} scale={0.509}>
          <mesh name="LUCA_Icon" geometry={nodes.LUCA_Icon.geometry} material={materials.Icons} position={[-0.12, -0.019, 1.063]} rotation={[Math.PI / 2, 0, 0]} scale={0.561} />
        </mesh>
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Tree} position={[1.247, -4.049, 1.436]} rotation={[Math.PI / 2, 0, 0]} scale={[6.678, 3.04, 3.047]} />
        <mesh name="Cars" geometry={nodes.Cars.geometry} material={materials['Material.006']} position={[38.398, 1.604, 0.308]} rotation={[-Math.PI, 0.317, -Math.PI]} scale={1.22}>
          <mesh name="Cars_Icon" geometry={nodes.Cars_Icon.geometry} material={materials.Icons} position={[0.052, 0.07, 0.518]} rotation={[Math.PI / 2, 0, 0]} scale={1.902} />
          <mesh name="Cars_Text" geometry={nodes.Cars_Text.geometry} material={materials.Icons} position={[0.208, -0.238, 0.504]} rotation={[Math.PI / 2, 0, 0]} scale={0.77} />
        </mesh>
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[3.417, 1.011, -2.809]} scale={-2564.796} />
        <mesh name="Biomass_Text" geometry={nodes.Biomass_Text.geometry} material={materials.Icons} position={[4.018, -6.349, -3.633]} rotation={[-Math.PI / 2, 0, 2.934]} scale={3.6} />
        <mesh name="Technomass_Text" geometry={nodes.Technomass_Text.geometry} material={materials.Icons} position={[9.627, -16.697, -3.633]} rotation={[-Math.PI / 2, 0, -3.012]} scale={3.6} />
        <mesh name="Plastics_Hover" geometry={nodes.Plastics_Hover.geometry} material={nodes.Plastics_Hover.material} position={[2.962, 0.985, 13.314]} rotation={[0, 0.488, 0]} scale={[0.784, 0.013, 0.784]} />
        <mesh name="Metals_Hover" geometry={nodes.Metals_Hover.geometry} material={nodes.Metals_Hover.material} position={[3.987, 1, 10.69]} rotation={[0, 0.488, 0]} scale={[1.318, 0.175, 1.318]} />
        <mesh name="Asphalt_Hover" geometry={nodes.Asphalt_Hover.geometry} material={nodes.Asphalt_Hover.material} position={[5.761, 0.923, 6.778]} rotation={[0, 0.488, 0]} scale={[1.486, 0.024, 1.486]} />
        <mesh name="Bricks_Hover" geometry={nodes.Bricks_Hover.geometry} material={nodes.Bricks_Hover.material} position={[8.237, 0.995, 2.599]} rotation={[0, 0.488, 0]} scale={[1.766, 0.275, 1.69]} />
        <mesh name="Aggregates_Hover" geometry={nodes.Aggregates_Hover.geometry} material={nodes.Aggregates_Hover.material} position={[10.591, 0.995, -3.136]} rotation={[0, 0.488, 0]} scale={[2.835, 0.106, 2.888]} />
        <mesh name="Concrete_Hover" geometry={nodes.Concrete_Hover.geometry} material={nodes.Concrete_Hover.material} position={[14.767, 0.995, -10.248]} rotation={[0, 0.488, 0]} scale={[3.244, 0.029, 3.181]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.007']} position={[2.952, 1.018, 13.31]} rotation={[0, 0.494, 0]} scale={[0.075, 0.4, 0.075]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.007']} position={[3.941, 1.018, 10.675]} rotation={[0, 0.494, 0]} scale={[0.075, 0.643, 0.075]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.007']} position={[5.795, 1.018, 6.829]} rotation={[0, 0.494, 0]} scale={[0.075, 0.759, 0.075]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.007']} position={[8.31, 1.018, 2.542]} rotation={[0, 0.494, 0]} scale={[0.075, 0.884, 0.075]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.007']} position={[10.602, 1.018, -3.055]} rotation={[0, 0.494, 0]} scale={[0.075, 1.389, 0.075]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.007']} position={[14.742, 1.018, -10.155]} rotation={[0, 0.494, 0]} scale={[0.075, 1.589, 0.075]} />
        <mesh name="Humans" geometry={nodes.Humans.geometry} material={materials['Material.003']} position={[0.194, -15.072, 9.418]} rotation={[Math.PI / 2, 0, 0.43]}>
          <mesh name="Humans_Icon" geometry={nodes.Humans_Icon.geometry} material={materials.Icons} position={[0.002, 0.209, 0.003]} scale={0.616} />
        </mesh>
        <mesh name="Concrete" geometry={nodes.Concrete.geometry} material={materials.Concrete} position={[79.308, -2.192, -89.689]} rotation={[0, 0.488, 0]} scale={6.499}>
          <mesh name="Concrete_Icon" geometry={nodes.Concrete_Icon.geometry} material={materials.Icons} position={[-0.025, -0.003, 0.504]} rotation={[Math.PI / 2, 0, 0]} scale={[0.417, 0.419, 0.419]} />
          <mesh name="Concrete_Text" geometry={nodes.Concrete_Text.geometry} material={materials.Icons} position={[-0.097, -0.016, 0.508]} rotation={[Math.PI / 2, 0, 0.055]} scale={0.145} />
        </mesh>
        <mesh name="Bricks" geometry={nodes.Bricks.geometry} material={materials.Bricks} position={[72.89, -0.201, -76.929]} rotation={[0, 0.488, 0]} scale={3.583}>
          <mesh name="Bricks_Icon" geometry={nodes.Bricks_Icon.geometry} material={materials.Icons} position={[-0.006, -0.02, 0.537]} rotation={[Math.PI / 2, 0, 0]} scale={0.708} />
          <mesh name="Bricks_Text" geometry={nodes.Bricks_Text.geometry} material={materials.Icons} position={[-0.082, -0.109, 0.52]} rotation={[Math.PI / 2, 0, 0.055]} scale={0.221} />
        </mesh>
        <mesh name="Metals" geometry={nodes.Metals.geometry} material={materials.Metal} position={[68.558, -0.257, -68.771]} rotation={[0, 0.488, 0]} scale={[2.692, 2.555, 2.555]}>
          <mesh name="Metals_Icon" geometry={nodes.Metals_Icon.geometry} material={materials.Icons} position={[0.002, -0.005, 0.519]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.304, 0.358, 0.321]} />
          <mesh name="Metals_Text" geometry={nodes.Metals_Text.geometry} material={materials.Icons} position={[-0.109, -0.245, 0.511]} rotation={[1.571, 0.002, -0.036]} scale={[0.297, 0.313, 0.313]} />
        </mesh>
        <mesh name="Aggregates" geometry={nodes.Aggregates.geometry} material={materials.Aggregates} position={[75.129, -1.84, -82.57]} rotation={[0, 0.488, 0]} scale={5.779}>
          <mesh name="Aggregates_Icon" geometry={nodes.Aggregates_Icon.geometry} material={materials.Icons} position={[0.016, 0.02, 0.499]} rotation={[Math.PI / 2, 0, 0]} scale={0.504} />
          <mesh name="Aggregates_Text" geometry={nodes.Aggregates_Text.geometry} material={materials.Icons} position={[0.076, 0.044, 0.515]} rotation={[Math.PI / 2, 0, 0.056]} scale={0.152} />
        </mesh>
        <mesh name="Asphalt" geometry={nodes.Asphalt.geometry} material={materials.Asphalt} position={[70.357, -0.579, -72.647]} rotation={[0, 0.488, 0]} scale={3.191}>
          <mesh name="Asphalt_Icon" geometry={nodes.Asphalt_Icon.geometry} material={materials.Icons} position={[-0.003, 0.016, 0.581]} rotation={[Math.PI / 2, 0, 0]} scale={0.559} />
          <mesh name="Asphalt_Text" geometry={nodes.Asphalt_Text.geometry} material={materials.Icons} position={[-0.099, -0.116, 0.564]} rotation={[Math.PI / 2, 0, 0.056]} scale={0.29} />
        </mesh>
        <mesh name="Plastics" geometry={nodes.Plastics.geometry} material={materials.Plastics} position={[67.527, 0.193, -66.148]} rotation={[0, 0.488, 0]} scale={1.623}>
          <mesh name="Plastics_Icon" geometry={nodes.Plastics_Icon.geometry} material={materials.Icons} position={[-0.004, 0.062, 0.504]} rotation={[Math.PI / 2, 0, 0]} scale={0.616} />
          <mesh name="Plastics_Text" geometry={nodes.Plastics_Text.geometry} material={materials.Icons} position={[-0.227, -0.454, 0.512]} rotation={[Math.PI / 2, 0, -0.004]} scale={0.517} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Part01.glb')
