/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/globe.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'

export function Globe(props) {
  const { nodes, materials } = useGLTF('globe.glb')

  const globeRef = useRef()
  
  const globeHover = (e) => {
    document.body.style.cursor = 'pointer';
  }
  const globeUnhover = (e) => {
    document.body.style.cursor = 'auto';

  }
  useFrame((state, delta) => {
        globeRef.current.rotation.y -= 1 * delta
  })

  return (
    <group ref = {globeRef} {...props} dispose={null}>
      <mesh geometry={nodes.Globe.geometry} material={materials.Material_Test} position={[0, 13.43, 0]} 
      rotation={[1.96, -0.05, 0.02]} scale={9.47} 
      onPointerOver={globeHover}  onPointerOut = {globeUnhover} 
      onClick={()=>{props.setCounter(props.counter+1)}}
      
      />
    </group>
  )
}

useGLTF.preload('globe.glb')
